version: '2'
services:
  web:
    build: ./
    image: asteria
    ports:
      - 8080:80
    working_dir: /var/www/html
    volumes:
      - ./www/asteria:/var/www/html
      - ./apache.conf:/etc/apache2/sites-available/000-default.conf
    links:
    - mysql:mysql
  composer:
    restart: 'no'
    image: composer/composer:php7
    command: update
    working_dir: /var/www
    volumes:
    - ./www/asteria:/var/www
  mysql:
    image: mysql:5.6
    volumes:
    - ./server/var/lib/mysql:/var/lib/mysql
    - ./server/root:/root
    ports:
    - "4418:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=asteria
